In [1]:
import pandas as pd
import numpy as np

In [4]:
import os

os.listdir(".")

['brfss_env',
 'LLCP2024.XPT',
 '.DS_Store',
 'LLCP2021.XPT',
 'LLCP2020.XPT',
 'LLCP2022.XPT',
 'LLCP2023.XPT',
 'brfss_preprocess.ipynb']

In [5]:
import pandas as pd

brfss_2020 = pd.read_sas("LLCP2020.XPT", format="xport")

brfss_2020.shape

(401958, 279)

In [7]:
brfss_2020.columns.tolist()

['_STATE',
 'FMONTH',
 'IDATE',
 'IMONTH',
 'IDAY',
 'IYEAR',
 'DISPCODE',
 'SEQNO',
 '_PSU',
 'CTELENM1',
 'PVTRESD1',
 'COLGHOUS',
 'STATERE1',
 'CELPHONE',
 'LADULT1',
 'COLGSEX',
 'NUMADULT',
 'LANDSEX',
 'NUMMEN',
 'NUMWOMEN',
 'RESPSLCT',
 'SAFETIME',
 'CTELNUM1',
 'CELLFON5',
 'CADULT1',
 'CELLSEX',
 'PVTRESD3',
 'CCLGHOUS',
 'CSTATE1',
 'LANDLINE',
 'HHADULT',
 'SEXVAR',
 'GENHLTH',
 'PHYSHLTH',
 'MENTHLTH',
 'POORHLTH',
 'HLTHPLN1',
 'PERSDOC2',
 'MEDCOST',
 'CHECKUP1',
 'EXERANY2',
 'SLEPTIM1',
 'CVDINFR4',
 'CVDCRHD4',
 'CVDSTRK3',
 'ASTHMA3',
 'ASTHNOW',
 'CHCSCNCR',
 'CHCOCNCR',
 'CHCCOPD2',
 'HAVARTH4',
 'ADDEPEV3',
 'CHCKDNY2',
 'DIABETE4',
 'DIABAGE3',
 'LASTDEN4',
 'RMVTETH4',
 'MARITAL',
 'EDUCA',
 'RENTHOM1',
 'NUMHHOL3',
 'NUMPHON3',
 'CPDEMO1B',
 'VETERAN3',
 'EMPLOY1',
 'CHILDREN',
 'INCOME2',
 'PREGNANT',
 'WEIGHT2',
 'HEIGHT3',
 'DEAF',
 'BLIND',
 'DECIDE',
 'DIFFWALK',
 'DIFFDRES',
 'DIFFALON',
 'SMOKE100',
 'SMOKDAY2',
 'STOPSMK2',
 'LASTSMK2',
 'USENOW3',
 'ALCDAY5',
 'AVEDRNK3',
 'DRNK3GE5',
 'MAXDRNKS',
 'FLUSHOT7',
 'FLSHTMY3',
 'SHINGLE2',
 'PNEUVAC4',
 'FALL12MN',
 'FALLINJ4',
 'SEATBELT',
 'DRNKDRI2',
 'HADMAM',
 'HOWLONG',
 'HADPAP2',
 'LASTPAP2',
 'HPVTEST',
 'HPLSTTST',
 'HADHYST2',
 'PCPSAAD3',
 'PCPSADI1',
 'PCPSARE1',
 'PSATEST1',
 'PSATIME',
 'PCPSARS1',
 'COLNSCPY',
 'COLNTEST',
 'SIGMSCPY',
 'SIGMTEST',
 'BLDSTOL1',
 'LSTBLDS4',
 'STOOLDNA',
 'SDNATEST',
 'VIRCOLON',
 'VCLNTEST',
 'HIVTST7',
 'HIVTSTD3',
 'HIVRISK5',
 'PDIABTST',
 'PREDIAB1',
 'INSULIN1',
 'BLDSUGAR',
 'FEETCHK3',
 'DOCTDIAB',
 'CHKHEMO3',
 'FEETCHK',
 'EYEEXAM1',
 'DIABEYE',
 'DIABEDU',
 'TOLDCFS',
 'HAVECFS',
 'WORKCFS',
 'TOLDHEPC',
 'TRETHEPC',
 'PRIRHEPC',
 'HAVEHEPC',
 'HAVEHEPB',
 'MEDSHEPB',
 'HLTHCVR1',
 'CIMEMLOS',
 'CDHOUSE',
 'CDASSIST',
 'CDHELP',
 'CDSOCIAL',
 'CDDISCUS',
 'CAREGIV1',
 'CRGVREL4',
 'CRGVLNG1',
 'CRGVHRS1',
 'CRGVPRB3',
 'CRGVALZD',
 'CRGVPER1',
 'CRGVHOU1',
 'CRGVEXPT',
 'ECIGARET',
 'ECIGNOW',
 'MARIJAN1',
 'USEMRJN2',
 'RSNMRJN1',
 'LCSFIRST',
 'LCSLAST',
 'LCSNUMCG',
 'LCSCTSCN',
 'CNCRDIFF',
 'CNCRAGE',
 'CNCRTYP1',
 'CSRVTRT3',
 'CSRVDOC1',
 'CSRVSUM',
 'CSRVRTRN',
 'CSRVINST',
 'CSRVINSR',
 'CSRVDEIN',
 'CSRVCLIN',
 'CSRVPAIN',
 'CSRVCTL2',
 'PCPSADE1',
 'PCDMDEC1',
 'HPVADVC4',
 'HPVADSHT',
 'TETANUS1',
 'IMFVPLA1',
 'BIRTHSEX',
 'SOMALE',
 'SOFEMALE',
 'TRNSGNDR',
 'ACEDEPRS',
 'ACEDRINK',
 'ACEDRUGS',
 'ACEPRISN',
 'ACEDIVRC',
 'ACEPUNCH',
 'ACEHURT1',
 'ACESWEAR',
 'ACETOUCH',
 'ACETTHEM',
 'ACEHVSEX',
 'RCSGENDR',
 'RCSRLTN2',
 'CASTHDX2',
 'CASTHNO2',
 'QSTVER',
 'QSTLANG',
 '_METSTAT',
 '_URBSTAT',
 'MSCODE',
 '_STSTR',
 '_STRWT',
 '_RAWRAKE',
 '_WT2RAKE',
 '_IMPRACE',
 '_CHISPNC',
 '_CRACE1',
 '_CPRACE',
 '_CLLCPWT',
 '_DUALUSE',
 '_DUALCOR',
 '_LLCPWT2',
 '_LLCPWT',
 '_RFHLTH',
 '_PHYS14D',
 '_MENT14D',
 '_HCVU651',
 '_TOTINDA',
 '_MICHD',
 '_LTASTH1',
 '_CASTHM1',
 '_ASTHMS1',
 '_DRDXAR2',
 '_EXTETH3',
 '_ALTETH3',
 '_DENVST3',
 '_PRACE1',
 '_MRACE1',
 '_HISPANC',
 '_RACE',
 '_RACEG21',
 '_RACEGR3',
 '_RACEPRV',
 '_SEX',
 '_AGEG5YR',
 '_AGE65YR',
 '_AGE80',
 '_AGE_G',
 'HTIN4',
 'HTM4',
 'WTKG3',
 '_BMI5',
 '_BMI5CAT',
 '_RFBMI5',
 '_CHLDCNT',
 '_EDUCAG',
 '_INCOMG',
 '_SMOKER3',
 '_RFSMOK3',
 'DRNKANY5',
 'DROCDY3_',
 '_RFBING5',
 '_DRNKWK1',
 '_RFDRHV7',
 '_FLSHOT7',
 '_PNEUMO3',
 '_RFSEAT2',
 '_RFSEAT3',
 '_DRNKDRV',
 '_RFMAM22',
 '_MAM5023',
 '_RFPAP35',
 '_RFPSA23',
 '_CLNSCPY',
 '_SGMSCPY',
 '_SGMS10Y',
 '_RFBLDS4',
 '_STOLDNA',
 '_VIRCOLN',
 '_SBONTIM',
 '_CRCREC1',
 '_AIDTST4']

In [8]:
cols_needed = [
    "_STATE",
    "_LLCPWT",
    "_BMI5",
    "_AGEG5YR",
    "_SEX",
    "_EDUCAG",
    "_INCOMG",
    "_RACE"
]

brfss_2020 = brfss_2020[cols_needed]

brfss_2020.head()

   _STATE      _LLCPWT   _BMI5  _AGEG5YR  _SEX  _EDUCAG  _INCOMG  _RACE
0     1.0   284.335672  1660.0       8.0   2.0      4.0      1.0    1.0
1     1.0   171.283329  2918.0      10.0   2.0      4.0      9.0    2.0
2     1.0  1334.368863     NaN      10.0   2.0      3.0      5.0    2.0
3     1.0  1297.486618     NaN      13.0   2.0      2.0      9.0    1.0
4     1.0   454.815127  2034.0      13.0   2.0      4.0      9.0    1.0

In [9]:
brfss_2020.shape

(401958, 8)

In [10]:
brfss_2020["BMI"] = brfss_2020["_BMI5"] / 100

In [11]:
brfss_2020["obese"] = (brfss_2020["BMI"] >= 30).astype(int)

In [12]:
brfss_2020 = brfss_2020[
    (brfss_2020["_BMI5"] < 9000) &
    (brfss_2020["_BMI5"] > 1200)
]

In [13]:
brfss_2020 = brfss_2020[
    (brfss_2020["_AGEG5YR"] < 14) &
    (brfss_2020["_SEX"] < 3) &
    (brfss_2020["_EDUCAG"] < 5) &
    (brfss_2020["_INCOMG"] < 6)
]

brfss_2020.shape

(300259, 10)

In [14]:
brfss_2020["year"] = 2020

In [16]:
brfss_2020 = brfss_2020.rename(columns={"_INCOMG": "_INCOMG1"})

In [17]:
brfss_2020.head()

,_STATE,_LLCPWT,_BMI5,_AGEG5YR,_SEX,_EDUCAG,_INCOMG1,_RACE,BMI,obese,year
0,1.0,284.335672,1660.0,8.0,2.0,4.0,1.0,1.0,16.60,0,2020
5,1.0,616.146154,2658.0,10.0,1.0,2.0,3.0,1.0,26.58,0,2020
6,1.0,341.379354,2421.0,12.0,2.0,2.0,4.0,1.0,24.21,0,2020
7,1.0,333.450142,2657.0,10.0,2.0,2.0,3.0,2.0,26.57,0,2020
8,1.0,1627.016526,2371.0,5.0,2.0,4.0,4.0,1.0,23.71,0,2020

In [18]:
brfss_2020.to_csv("brfss_clean_2020.csv", index=False)

In [19]:
import pandas as pd

files = [
    "LLCP2020.XPT",
    "LLCP2021.XPT",
    "LLCP2022.XPT",
    "LLCP2023.XPT",
    "LLCP2024.XPT"
]

required_vars = [
    "_STATE",
    "_LLCPWT",
    "_BMI5",
    "_AGEG5YR",
    "_SEX",
    "_EDUCAG",
    "_RACE"
]

for f in files:
    df = pd.read_sas(f, format="xport", encoding="latin1")
    print(f"\nChecking {f}")
    
    missing = [v for v in required_vars if v not in df.columns]
    
    if len(missing) == 0:
        print("All required variables present")
    else:
        print("Missing:", missing)

Checking LLCP2020.XPT
All required variables present

Checking LLCP2021.XPT
All required variables present

Checking LLCP2022.XPT
Missing: ['_RACE']

Checking LLCP2023.XPT
All required variables present

Checking LLCP2024.XPT
All required variables present

In [21]:
df_2022 = pd.read_sas("LLCP2022.XPT", format="xport", encoding="latin1")

[c for c in df_2022.columns if "RACE" in c]

['_IMPRACE',
 '_CRACE2',
 '_CPRACE2',
 '_PRACE2',
 '_MRACE2',
 '_RACE1',
 '_RACEG22',
 '_RACEGR4',
 '_RACEPR1']

In [22]:
df_2022["_RACEGR4"].value_counts().head()

_RACEGR4
1.0    320421
5.0     42917
2.0     35446
3.0     22713
9.0     14055
Name: count, dtype: int64

In [20]:
files = [
    "LLCP2020.XPT",
    "LLCP2021.XPT",
    "LLCP2022.XPT",
    "LLCP2023.XPT",
    "LLCP2024.XPT"
]

for f in files:
    df = pd.read_sas(f, format="xport", encoding="latin1")
    
    income_vars = [c for c in df.columns if "INCOM" in c]
    
    print(f)
    print(income_vars)
    print()

LLCP2020.XPT
['INCOME2', '_INCOMG']

LLCP2021.XPT
['INCOME3', '_INCOMG1']

LLCP2022.XPT
['INCOME3', '_INCOMG1']

LLCP2023.XPT
['INCOME3', '_INCOMG1']

LLCP2024.XPT
['INCOME3', '_INCOMG1']

In [23]:
def preprocess_brfss(file, year):

    df = pd.read_sas(file, format="xport", encoding="latin1")

    # Fix income variable (2020)
    if year == 2020:
        df = df.rename(columns={"_INCOMG": "_INCOMG1"})

    # Fix race variable (2022+)
    if year >= 2022:
        df = df.rename(columns={"_RACEGR4": "_RACE"})

    cols_needed = [
        "_STATE",
        "_LLCPWT",
        "_BMI5",
        "_AGEG5YR",
        "_SEX",
        "_EDUCAG",
        "_INCOMG1",
        "_RACE"
    ]

    df = df[cols_needed]

    # Convert BMI
    df["BMI"] = df["_BMI5"] / 100

    # Obesity indicator
    df["obese"] = (df["BMI"] >= 30).astype(int)

    # Remove invalid BMI
    df = df[(df["_BMI5"] < 9000) & (df["_BMI5"] > 1200)]

    # Remove missing demographics
    df = df[
        (df["_AGEG5YR"] < 14) &
        (df["_SEX"] < 3) &
        (df["_EDUCAG"] < 5) &
        (df["_INCOMG1"] < 6)
    ]

    df["year"] = year

    return df

In [24]:
brfss_2021 = preprocess_brfss("LLCP2021.XPT", 2021)
brfss_2022 = preprocess_brfss("LLCP2022.XPT", 2022)
brfss_2023 = preprocess_brfss("LLCP2023.XPT", 2023)
brfss_2024 = preprocess_brfss("LLCP2024.XPT", 2024)

In [25]:
print(brfss_2021.shape)
print(brfss_2022.shape)
print(brfss_2023.shape)
print(brfss_2024.shape)

(239678, 11)
(235582, 11)
(227847, 11)
(241343, 11)

In [26]:
brfss_all = pd.concat([
    brfss_2020,
    brfss_2021,
    brfss_2022,
    brfss_2023,
    brfss_2024
], ignore_index=True)

brfss_all.shape

(1244709, 11)

In [27]:
brfss_all.groupby("year")["obese"].mean()

year
2020    0.330072
2021    0.363617
2022    0.361836
2023    0.357679
2024    0.364651
Name: obese, dtype: float64

In [28]:
brfss_all["year"].value_counts().sort_index()

year
2020    300259
2021    239678
2022    235582
2023    227847
2024    241343
Name: count, dtype: int64

In [29]:
brfss_all.to_csv("brfss_clean_2020_2024.csv", index=False)